### ISSUE TITLE
Q: How to get daily usage graphs in HA?

### ISSUE THREAD

**Issue by jgclark** [BottlecapDave/HomeAssistant-OctopusEnergy#87] opened 2022-11-05 09:07 UTC
A Question, not an Issue.
I have set up Statistics card for my electricity usage, but as the feeds are cumulative, naturally the graph just goes up and up, which isn't easy to read. How are you all getting more traditional daily usage graphs in HA?
![image](https://user-images.githubusercontent.com/1671754/200112334-e831251b-8067-4a49-8d77-6c158795b82a.jpeg)

**Comment by FalconUK** [comment] 2022-12-03 16:48
I just use a History graph.

![image](https://user-images.githubusercontent.com/77235040/205451969-a2a263eb-6816-4b88-92fd-946d1fee2bdf.png)

Dave is working on the zero value issue, it occurs every time HA restarts and the integration reloads.

**Comment by BottlecapDave** [comment] 2022-12-04 15:16
The zero issues should be fixed in the latest release https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v4.7.0

As for the accumulation, I think this is related to https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/79 which I'm currently investigating

**Comment by BottlecapDave** [comment] 2022-12-17 14:35
Hello. After further investigation I've found the culprit and released [v5.0.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.0.0). The cause of this was due to a misconfigured entity, which unfortunately has resulted in a fix which lose historic data. The full instructions can be found at https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/108.

I'm sorry that this is the outcome.

**Closed** 2022-12-17 14:35 UTC
