### ISSUE TITLE
Current Consumption Negative Value at 00:00

### ISSUE THREAD

**Issue by roundyuk** [BottlecapDave/HomeAssistant-OctopusEnergy#672] opened 2024-01-04 00:39 UTC
### Describe the bug

For the last two days you energy dashboard is showing a negative value at 00:00, both very close to 23kWh.
![E8F7BB64-A2BF-40DE-94EE-554EE7E13B85](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65355138/59366ac6-00cc-4360-bbde-49617e0cecf3)

### Reproduction steps

Issue is constant, no changes to current consumption entity being selected for the energy dashboard.

### Expected behaviour

Should not show negative as I have no return to the grid at my property.

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-H

### Integration Version

9.2.1

### Home Assistant Version

2023.12.4

### Fresh Install?

Not specified

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by mateuszdrab** [comment] 2024-01-04 05:01
I had the same issue, had to roll back to version 9.1.0 from 9.2.1

**Comment by BottlecapDave** [comment] 2024-01-04 06:41
Hello. Sorry you're seeing this. If you haven't done anything and this has only just started happening, then it suggests the data coming back from OE API is broken (which is out of my control). I've added some additional logging for the next release, so once released (V10) you'll need to follow the [faq instructions]( https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq/#how-do-i-increase-the-logs-for-the-integration) to increase and obtain debug logging information. I'll need the logs for the hour before and hour after the culprit time period.

**Comment by roundyuk** [comment] 2024-01-04 09:57
Interesting, so would that imply code issue as opposed to data from the API?

Chris

On 4 Jan 2024 05:01, Mateusz Drab ***@***.***> wrote:

I had the same issue, had to roll back to version 9.1.0 from 9.2.1

**Comment by BottlecapDave** [comment] 2024-01-04 17:10
Not necessarily. All of the current consumption sensors are driven from the same retrieved data, half hourly breakdowns for the current day. This is to reduce load on the APIs and to account for enforced rate limits.

The current accumulative sensor take this data and just add it up, so you can see it gradually go up for each day and then reset. This would go down, only if octopus adjusted the data for the day in a way that was less than the previous retrieval.

The current sensor takes these accumulatives and calculates the delta between updates, unless it's the start of the day, in which case it'll take the absolute value for the day. As with the above sensor, this sensor might go negative if octopus adjust the data in some way. The only way it could go negative is if the data is adjusted in a negative way for the hour or if there's a floating point issue in either the calculation for the sensor or the calculation by the energy dashboard. The additional logging should confirm this either way.

**Comment by BottlecapDave** [comment] 2024-01-04 17:12
One additional question would be what does the history look like for the time period for the current consumption sensor

**Comment by roundyuk** [comment] 2024-01-04 19:13
Interesting, this is the history vs. what the Octopus data is showing..?

[A screenshot of a computer  Description automatically generated]
[A screen shot of a graph  Description automatically generated]

Today seems to be back to normal…

**Comment by BottlecapDave** [comment] 2024-01-04 19:14
Screenshots don't seem to be included in the reply

**Comment by roundyuk** [comment] 2024-01-04 19:19
Here is the raw data from Octopus..

**Comment by roundyuk** [comment] 2024-01-04 19:19
[consumption.csv](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/13834548/consumption.csv)

Adding here in case attachment dropped

**Comment by roundyuk** [comment] 2024-01-04 19:20
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65355138/15bab4fb-546e-4d19-acec-ce05c3a70b03)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65355138/a84f1c2d-4500-4ae6-ab81-110bf7d12d85)

**Comment by mateuszdrab** [comment] 2024-01-05 17:57
For me, it looked like this

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26556541/690f4dd4-5bab-4b41-9b54-36c8464c59e3)

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26556541/8cd4e458-54a4-465c-a446-7d883a83ec7e)

Something was causing the utility meter integration to register a massive usage reading at midnight - all of this stopped after reverting to v9.1.0 so it might be something to do with [the API ](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/commit/d461718504243bcd0d6e304c85eb21d7967d54fc)

I notice v10 is out - keen to give it a shot but don't want to mess up my stats.

**Comment by mateuszdrab** [comment] 2024-01-05 21:07
> Very odd as nothing changed in between then and now around the frequency of the current consumption data updates other than some additional retry logic which backs off. Do any of you have failures to retrieve current consumption around that time in your logs (they would be warnings)?

I might have to increase verbosity and let it run on the new version for a bit. I'll configure it on a test instance. But I'll check the existing logs before I do that.

**Comment by BottlecapDave** [comment] 2024-01-05 21:20
> Something was causing the utility meter integration to register a massive usage reading at midnight

The utility meter has issues with the sensors as it takes the state when _any_ of the data on the sensor updates (including attributes). People have got around this by creating a template sensor which omits the attribute changes and just republishes the state - it's not great, but the attribute data is useful and needed but the utility meter has no way of determining the difference between a state change and an attribute chage. I really need to update the FAQ on this.

**Comment by BottlecapDave** [comment] 2024-01-05 21:22
What does the history look like for the raw current consumption entity during the positive or negative spike? I've seen [reports](https://community.home-assistant.io/t/negative-values-in-energy-dashboard-since-last-update/568990) of other people complaining of spikes in their energy dashboard but for sensors not linked to this integration and wondering if it's something similar.

**Comment by roundyuk** [comment] 2024-01-05 23:40
Hey, do you mean the raw current demand entity vs. current consumption? Interesting though, the demand had a spike yes...up to 3kW and there was nothing running to pull that sort of juice at that time I don't recall.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/65355138/ce55a466-769c-4daa-8e2a-91b8cdb897c8)

**Comment by BottlecapDave** [comment] 2024-01-08 17:44
Hmm the demand being so high probably doesnt help. The current consumption going negative is interesting as at that point it should be the raw total reported by the API implying it's an API issue. If someone could get me the additional logs as requested this will help confirm this situation.

**Comment by mateuszdrab** [comment] 2024-01-08 18:17
I just set up a repro in my test HA instance with the same version of the integration and as I was configuring the energy features, I realized that I was still using an utility meter helper which was based on the total Electricity Current Consumption entity with delta option enabled. 

Is this the right way to have this done?

I also enabled debug logs so we should have something soon.

**Comment by roundyuk** [comment] 2024-01-08 22:39
Have enabled debug but I haven’t seen the issue repeat.

Something of note though, my low carbon energy entity recorded -1309% and 351% on the two days where I have the weird values!

**Comment by BottlecapDave** [comment] 2024-01-09 06:40
Thanks for the efforts. Because this behaviour is different for everyone and not experienced by everyone (I'd expect this thread to be more active) I'm still convinced it's some dodgy data coming back from the API. But I'll await for the results before I pass blame :) 

@mateuszdrab you shouldn't need the utility sensor for energy dashboard as the sensors by themselves should work as is. Please follow the guide in the docs for optimal setup. If you're wanting to use the utility meter som additional work is needed to get it to work - see https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/672#issuecomment-1879270446

**Comment by mateuszdrab** [comment] 2024-01-09 14:15
I've reconfigured my Energy dashboard to use the sources as defined in the user manual and I can see that it looks all good now even for the historic dates which were showing improperly before.

However, as the current consumption sensor still contains the erroneous values, it either must have been an API issue with Octopus or something with the version of the integration as I was able to reproduce the issue on my dev instance overnight.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26556541/a358fb11-a2e9-4b43-8fef-7d4faa1ceda1)

On my prod instance with integration at 9.1.0 it looks like this

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26556541/6044bbe4-a527-4350-97c1-67fceb9f0af4)

It only happens for Gas on the prod instance, both are affected on the dev instance.

Could it be something with the retry logic that was added?

[Explore-logs-2024-01-09 14_11_10.txt](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/13874817/Explore-logs-2024-01-09.14_11_10.txt)

Attached a slightly redacted log file

**Comment by BottlecapDave** [comment] 2024-01-10 06:52
Thanks for the logs. I think I may have worked out the issue (just need to fix it now). Based on the logs it looks like your instance failed to retrieve the data as it crossed over the midnight threshold. I think this then caused the sensor to use the previous days worth of data as it's baseline for the new day, which causes the huge positive spike. When the correct data is finally pulled for the day this causes the negative spike (as it's much lower that the final value of the previous day) to correct the data. I'll try and look at the fix for this issue over the next week.

**Comment by mateuszdrab** [comment] 2024-01-10 08:40
> Thanks for the logs. I think I may have worked out the issue (just need to fix it now). Based on the logs it looks like your instance failed to retrieve the data as it crossed over the midnight threshold. I think this then caused the sensor to use the previous days worth of data as it's baseline for the new day, which causes the huge positive spike. When the correct data is finally pulled for the day this causes the negative spike (as it's much lower that the final value of the previous day) to correct the data. I'll try and look at the fix for this issue over the next week.

That's great, take your time and let me know if you need anything.

Thanks for your work

**Comment by roundyuk** [comment] 2024-01-10 13:11
Late to the party, but my debug logs if it helps!
[home-assistant_octopus_energy_2024-01-10T13-09-14.273Z.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/13888065/home-assistant_octopus_energy_2024-01-10T13-09-14.273Z.log)

**Comment by adam-cobb** [comment] 2024-01-16 16:00
Just realised that this looks to be the same issue I am seeing and reported separately in #669

**Comment by BottlecapDave** [comment] 2024-01-20 09:10
Hello. This should be fixed in the latest release (v10.0.3)

**Closed by BottlecapDave** 2024-01-20 09:10 UTC
Labels: bug
