### ISSUE TITLE
Target Attributes don't seem right

### ISSUE THREAD

**Issue by Stephens-ely** [BottlecapDave/HomeAssistant-OctopusEnergy#631] opened 2023-12-13 16:58 UTC
### Describe the bug

I have a target sensor with a offset of -00:02:00 called 'binary_sensor.octopus_energy_target_offset_best_agile_rate_am'

I'm a little confused by the attribute 'next_time' as it has a strange value of '2023-12-14T01:56:00+00:00' for a start period of '2023-12-14T02:00:00+00:00'

I feel sure these two values are usually 2 min part (as per the offset) but this is 4 minutes.

Is it me or is there something wrong ?
![Capture](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/114488267/8a5c730b-370d-429d-8b50-cff9d3b439c3)

### Reproduction steps

Define a target with an negative offset.

### Expected behaviour

The next_time and 'start' values should be (in this case) 2 mins a part

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-L

### Integration Version

9.1.0

### Home Assistant Version

2023.12.1

### Fresh Install?

Not specified

### Home Assistant Logs

nothing obvious in logs

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment] 2023-12-13 17:25
Hello. This sounds very much like a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/611. This will be fixed in the next version.

**Closed by BottlecapDave** 2023-12-13 17:25 UTC
Labels: bug
