### ISSUE TITLE
Feature Request: standing charge

### ISSUE THREAD

**Issue by ColinRobbins** [BottlecapDave/HomeAssistant-OctopusEnergy#101] opened 2022-12-10 22:10 UTC
**Describe the bug**

The integration returns the current electric / gas rate, but not the standing charge.

**Required behaviour**

Show the standing charge.

**Comment by BottlecapDave** [comment] 2022-12-11 09:48
The standing charge is currently available as an attribute on the previous accumulation cost entities. You can obtain this via the following template

```
{{ state_attr('sensor.octopus_energy_electricity_XXX_XXX_previous_accumulative_cost', 'standing_charge') }}
```

I'll have a look at refactoring and putting this on the current rate as well. I didn't put it as it's own entity as it rarely changes. Is this just for informative reasons, or is there something else you're wanting this information for?

**Comment by ColinRobbins** [comment] 2022-12-11 10:33
Thanks, I did see it in the previous cost sensor, but it does occasionally change, so would be good to see in the current rate.

It’s mainly for info.  But I have just installed Solar PV, so may need in in a template sensor to calculate cost savings.

**Comment by p6sfrx725z28knfy** [comment] 2022-12-12 10:42
> Thanks, I did see it in the previous cost sensor, but it does occasionally change, so would be good to see in the current rate.

I would also find this useful as I presently use another integration to get the current standing charge

**Comment by liamstears** [comment] 2022-12-13 02:50
> The standing charge is currently available as an attribute on the previous accumulation cost entities. You can obtain this via the following template
> 
> ```
> {{ state_attr('sensor.octopus_energy_electricity_XXX_XXX_previous_accumulative_cost', 'standing_charge') }}
> ```
> 
> I'll have a look at refactoring and putting this on the current rate as well. I didn't put it as it's own entity as it rarely changes. Is this just for informative reasons, or is there something else you're wanting this information for?

Although this use to work the 'standing_charge' attribute has disappeared for me...




> > Thanks, I did see it in the previous cost sensor, but it does occasionally change, so would be good to see in the current rate.
> 
> I would also find this useful as I presently use another integration to get the current standing charge

What integration do you use for this?

**Comment by BottlecapDave** [comment] 2022-12-17 15:04
I'll look at creating a new sensor that exposes the current standing charge.

@liamstears I'm a little worried that you said it disappeared as it shouldn't have. Which sensor has it disappeared from? Has it come back?

**Comment by liamstears** [comment] 2022-12-18 01:45
> I'll look at creating a new sensor that exposes the current standing charge.
> 
> @liamstears I'm a little worried that you said it disappeared as it shouldn't have. Which sensor has it disappeared from? Has it come back?

I'm afraid I can't be too helpful as I am not sure when they disappeared but I use to have the standing charge as an attribute on both electric and has meters but the attributes just disappeared quite some time ago although current rates and everything else still work as intended

New sensors that expose both gas and electric standing charges sound like a perfect solution to me if this can be done, thanks in advance for any/all help

**Comment by BottlecapDave** [comment] 2022-12-18 07:50
>  I use to have the standing charge as an attribute on both electric and gas meters but the attributes just disappeared quite some time ago

I'm guessing you're accumlative consumption and costs values are not updating as well then? As the standing charge gets populated at the same time.

**Comment by liamstears** [comment] 2022-12-18 15:52
> > I use to have the standing charge as an attribute on both electric and gas meters but the attributes just disappeared quite some time ago
> 
> I'm guessing you're accumulative consumption and costs values are not updating as well then? As the standing charge gets populated at the same time.

This is a possibility, unfortunately I've removed and readded the addon so I have no history to show/check but all accumulative costs at the moment are showing 0 indicating it's not coming through...

**Comment by BottlecapDave** [comment] 2022-12-28 10:25
Standing charges are now available as separate entities in https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v5.1.0. Closing issue, as this was the original request.

**Closed by BottlecapDave** 2022-12-28 10:25 UTC
Labels: enhancement, next-release
