### ISSUE TITLE
Target Rate Sensors Not Updating

### ISSUE THREAD

**Issue by martymcfly1** [BottlecapDave/HomeAssistant-OctopusEnergy#1047] opened 2024-10-27 12:46 UTC
### Describe the bug

Target rate sensors are not updating.  I’m getting the error message copied below in logs.

### Reproduction steps

Newly created Target Rate Sensors - following normal workflow through integration.  I’ve tried both standard and rolling sensors, both not updating and still getting the error message.

### Expected behaviour

Target rate sensors should be available, and should be updating (one should be on now based on what I’ve set up).

### Tariff Code

E-1R-AGILE-23-12-06-F

### Integration Version

13.0.3

### Home Assistant Version

2024.10.4

### Fresh Install?

After upgrading

### Home Assistant Logs

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/octopus_energy/target_rates/__init__.py:273
integration: Octopus Energy (documentation, issues)
First occurred: 12:39:51 (1 occurrences)
Last logged: 12:39:51

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/octopus_energy/target_rates/target_rate.py", line 237, in _handle_coordinator_update
    active_result = get_target_rate_info(current_date, self._target_rates, offset)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/target_rates/__init__.py", line 273, in get_target_rate_info
    "average_cost": total_cost / (minutes / 30),
                    ~~~~~~~~~~~^~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero


### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment] 2024-10-27 15:25
Hello. Sorry your're seeing this issue. Could you please let me know what config you've set up for the target rate senso so I can recreate the issue on my side.

**Comment by martymcfly1** [comment] 2024-10-27 15:38
No worries.  Here you go.  First sensor:

Hours required: 12.0
Defined Hours: Maximum
Type: Intermittent
Minimum Time To Start: 23:00
Maximum Time To Stop: 23:00
Maximum Rate For Target Hours: 0.20

Second Sensor:

Hours required: 4.0
Defined Hours: Minimum
Type: Intermittent
Minimum Time To Start: 23:00
Maximum Time To Stop: 23:00
Inverted Target Rates Is Checked
Minimum Rate For Target Hours: 0.21

**Comment by martymcfly1** [comment] 2024-10-27 16:15
I’ve noticed that my other target rate sensors are not updating either.  Everything was fine until I updated today.

**Comment by BottlecapDave** [comment] 2024-10-27 16:25
I believe this is related to the clocks going back last night where with the rates we effectively had two 01:00am periods. It should rectify itself when you go into the next period tonight. I'll have a look at trying to recreate it, but a fix won't be available until it probably fixes itself. Let me know if it doesn't fix itself and I'll take a deeper look.

**Comment by billmichell** [comment] 2024-10-27 17:21
Same here. All sensors, multiple configurations. Clock change seems too much of a coincidence, but of course there was also a version update.

**Comment by BottlecapDave** [comment] 2024-10-28 17:39
My test instance which is pointing at the above tariff and target rate sensors seem to be updating. Can either of you confirm this is a case? and if not, provide any further error logs?

I saw the mentioned error message once yesterday when I initially setup my instance to replicate the original issue, but it then disappeared once I restarted. I'm wondering if there was something dodgy in the data being returned by OE which has since been fixed which is why I can't recreate the issue in my tests.

**Comment by billmichell** [comment] 2024-10-28 17:55
Yeah, it stopped. Definitely dodgy data. Can’t be a coincidence that it happened on the clock change. Just an NPE. -- Bill MichellSent from my iPhoneOn 28 Oct 2024, at 17:40, David Kendall ***@***.***> wrote:﻿
My test instance which is pointing at the above tariff and target rate sensors seem to be updating. Can either of you confirm this is a case? and if not, provide any further error logs?
I saw the mentioned error message once yesterday when I initially setup my instance to replicate the original issue, but it then disappeared once I restarted. I'm wondering if there was something dodgy in the data being returned by OE which has since been fixed which is why I can't recreate the issue in my tests.

**Comment by BottlecapDave** [comment] 2024-10-28 17:59
Sorry @billmichell, are you saying the sensor is still not updating for you? If it's not updating, do you have any additional logs?

**Comment by billmichell** [comment] 2024-10-28 18:17
No it is updating now. -- Bill MichellSent from my iPhoneOn 28 Oct 2024, at 18:00, David Kendall ***@***.***> wrote:﻿
Sorry @billmichell, are you saying the sensor is still not updating for you? If it's not updating, do you have any additional logs?

**Comment by BottlecapDave** [comment] 2024-11-02 08:53
Ok thanks for the update. Is the sensor updating for you @martymcfly1 ?

**Comment by martymcfly1** [comment] 2024-11-02 09:23
> Ok thanks for the update. Is the sensor updating for you @martymcfly1 ?

Thanks Dave. Updated last night and all looks good.

**Comment by BottlecapDave** [comment] 2024-11-04 19:16
Some countermeasures for this has been added as part of [v13.1.0](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v13.1.0) along with some additional logging to try and track down the cause of the original issue. 

I'll close this issue for the moment as the original issue is no longer being observed, but raise a new ticket if you see it again.

**Closed by BottlecapDave** 2024-11-04 19:16 UTC
Labels: bug
