### ISSUE TITLE
Octopus Home Mini readings only updating every 30 minutes

### ISSUE THREAD

**Issue by joel-graham** [BottlecapDave/HomeAssistant-OctopusEnergy#925] opened 2024-06-18 13:06 UTC
### Describe the bug

The current consumption is only updating every 30 minutes.
```
# custom_components/octopus_energy/api_client/__init__.py
live_consumption_query = '''query {{
	smartMeterTelemetry(
    deviceId: "{device_id}"
    grouping: HALF_HOURLY 
		start: "{period_from}"
		end: "{period_to}"
	) {{
    readAt
    consumption
		consumptionDelta
    demand
	}}
}}'''
```

Should the "grouping" be a smaller time frame?

### Reproduction steps

Fresh HA installation with HACS and integrated into this repo.

### Expected behaviour

Meter Readings should update every minute.

### Tariff Code

E-1R-AGILE-24-04-03-A

### Integration Version

11.2.0

### Home Assistant Version

2024.6.3

### Fresh Install?

Fresh install

### Home Assistant Logs

N/A

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by joel-graham** [comment] 2024-06-18 13:06
P.S, this is my first issue contribution here, so apologies if the formatting is incorrect.

**Comment by BottlecapDave** [comment] 2024-06-18 16:29
Hello. Ther grouping has always been half hour and that's just consolidated the data into 30 minutes chunks to try and reduce the volume of data that is returned (1 minute intervals by the end of the day is far too much data).

This is also a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/914, so closing in favour of that. Please watch that issue for updates.

**Closed by BottlecapDave** 2024-06-18 16:29 UTC
Labels: bug

**Comment by joel-graham** [comment] 2024-06-18 16:30
Ah yes — thank you. Correct on duplicate, so will follow that thread. Thanks for taking the time to reply.
