### ISSUE TITLE
Unknown intelligent provider

### ISSUE THREAD

**Issue by majanson** [BottlecapDave/HomeAssistant-OctopusEnergy#1015] opened 2024-10-08 00:30 UTC
### Describe the bug

HA asked for a case to be raised for a provider named FORD.

Ford does allow for bump charging, changing the target charge percentage and the charge completion time.

Is there anything else you require from me to resolve this?

### Reproduction steps

Problem only appeared today after Ihad to reregister my car with Octopus Intelligent Go.

### Expected behaviour

Previously I could set the above details. Now I have two charger appear. One can change nothing and doesn't show intelligent dispatch. The other only had intelligent dispatch and nothing else.
![HA4](https://github.com/user-attachments/assets/7dfd0d4a-3523-4b13-9bd3-2714789bbf5d)
![HA3](https://github.com/user-attachments/assets/5d4d401a-85b1-4abe-abed-b3790ce19957)
![HA2](https://github.com/user-attachments/assets/22ab2d1b-7cd4-4438-86de-01d28345b5d1)
![HA1](https://github.com/user-attachments/assets/fce77112-da14-46dd-b677-754270bbacad)

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-A

### Integration Version

12.2.1

### Home Assistant Version

2024.10.1

### Fresh Install?

Not specified

### Home Assistant Logs

[octopus_energy-7686a9e2ab521921cdc61c8b6fb8aab1-Charger-609b8ae62109003d368f687ca9055bdc.json](https://github.com/user-attachments/files/17285783/octopus_energy-7686a9e2ab521921cdc61c8b6fb8aab1-Charger-609b8ae62109003d368f687ca9055bdc.json)
[octopus_energy-7686a9e2ab521921cdc61c8b6fb8aab1-Charger-d38b45375d1c2b6bdd43718bb61bf3f7.json](https://github.com/user-attachments/files/17285784/octopus_energy-7686a9e2ab521921cdc61c8b6fb8aab1-Charger-d38b45375d1c2b6bdd43718bb61bf3f7.json)

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment] 2024-10-08 05:27
Hello.  This is a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/1003. This will be resolved in the next release (due in about a week). If you can't wait, you can try the latest beta with the fix in it

**Closed by BottlecapDave** 2024-10-08 05:27 UTC
Labels: bug
