### ISSUE TITLE
Target Rate Sensor with price range 

### ISSUE THREAD

**Issue by beginner2047** [BottlecapDave/HomeAssistant-OctopusEnergy#836] opened 2024-04-16 08:06 UTC
### Describe the feature

Currently, the target rate sensor only search the minimum price but no limitation for the price. If the minimum price is 12p, it will also returnes. Can we add the maximum and or minimum for the price? So we don't need to create additional condition for automation.

As the return total hours (e.g 2 hours) may less than required hours (3 hours), an option should be provided to select return 0 (not meet required hours) or return as many as possible (2 hours). 

### Expected behaviour

user can define the price range in target rate. So the sensor will be on during that target rate period 

### Use Case

EV charger, we would like to define how many kwh is required based on unit rate. Cheaper unit rate charger more. For high unit rate, we may skip the charge times. 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [ ] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment] 2024-04-17 03:49
Hello. This is a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/423, so please follow that for progress.

**Closed by BottlecapDave** 2024-04-17 03:49 UTC
Labels: enhancement
