### ISSUE TITLE
Cosy6

### ISSUE THREAD

**Issue by nraimo1** [BottlecapDave/HomeAssistant-OctopusEnergy#988] opened 2024-08-30 18:21 UTC
### Describe the feature

Cosy6 should be reporting via api now if you want help with my cosy6 building this let me know 

### Expected behaviour

Cosy6

### Use Case

Heat pump control 

### Confirmation

- [X] By submitting this feature request, you agree that you have read the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy) and confirmed it does not already exist
- [X] I am willing/able to help contribute to the solution of this feature

**Comment by BottlecapDave** [comment] 2024-08-30 18:43
Hello and thanks for raising the fearure. I'll close this issue, as it's a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/972. Please follow upvote that issue and follow for updates.

**Closed by BottlecapDave** 2024-08-30 18:43 UTC
Labels: enhancement
