### ISSUE TITLE
Integration not picking up back-dated tariff changes

### ISSUE THREAD

**Issue by gcoan** [BottlecapDave/HomeAssistant-OctopusEnergy#756] opened 2024-02-15 11:00 UTC
### Describe the bug

I had an email yesterday from Octopus saying that they had noticed I was still on Flux Export as I had moved off Flux Import in October 2023, I shouldn’t be on Flux Export any more.
They would move me onto the 12 month fixed export (15p) tariff and back-date the change to when I moved off Flux onto Agile for my import.
The Octopus account showed my new export tariff straight away but the Octopus Integration didn’t.
I left it a while for the account refresh cycle to take effect, but the export tariff didn’t change.
Next morning I have looked again and the tariff via the Octopus API is still showing I’m on Flux Export

### Reproduction steps

Screen shot of my account details from Octopus API showing that the current tariff I’m on (end date in the future) is outgoing fixed:
![IMG_0601](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/142018870/5e1ebc32-d2d6-4ead-b9c1-fdc1e3851959)

Screen shot of my export rate from the Octopus Integration showing it still thinks I am on Octopus Flux:
![IMG_0602](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/142018870/f84bc40b-ebf7-4bb0-aa27-25f1e1aaf897)

I suspect the problem is due to the back-dated nature of my account tariff change and if I restarted Home Assistant it would correctly read my account details afresh from Octopus,  but I’ve not done that yet, as I think its still worth logging as it could well affect other people (or it may be something different)

### Expected behaviour

Account changes in Octopus are correctly reflected in the Octopus Integration API results

### Tariff Code

E-1R-FLUX-EXPORT-23-02-14-A

### Integration Version

10.1.0

### Home Assistant Version

2024.1.6

### Fresh Install?

After upgrading

### Home Assistant Logs

-

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by andreweacott** [comment] 2024-02-15 19:33
Fwiw, Octopus did the same to my account yesterday and the integration is also failing to reflect it.  Other apps that use the octopus API are showing the next export tariff it this HA integration is not

**Comment by BottlecapDave** [comment] 2024-02-16 03:55
I can see where the issue is. As @gcoan mentioned, if you reload the integration you should get the proper tariff. The integration will never be able to correct data that has already been calculated (e.g. previous consumption cost from 2 weeks ago) due to HA entities not liking their history changed. I should be able to get the stats that are used in the energy dashboard to update correctly.

**Comment by gcoan** [comment] 2024-02-16 17:57
So an update on this, short is I had to reboot Home Assistant and the Octopus Energy integration this morning (16th) just after midnight, and since the reboot it has correctly obtained the back dated export rates from Octopus.
Appreciate I can't restate history in HA, it was more about having the integration working going forward I was worried about.

The reason I had to reboot HA was that I spotted that the Octopus integration was in fact not getting any data from Octopus at all and hadn't been doing so since the 14th.  Standing charge was set to unknown and the current, previous and next day charges were all last updated on the 14th.
So the integration worked for the 15th when the 15th's rates were in the 'tomorrow' part, but after the 15th with no new rates, Predbat thought that all the import was zero cost - hence why I realised something was very wrong!

The reboot resolved it for me, but leaving it open if there's something that can be done to avoid the need for a reboot with back-dated tariff changes

**Comment by BottlecapDave** [comment] 2024-02-16 18:04
People have had issues over the last couple of days as OE seemed to have transitioned a lot of people across to new versions of their tariffs, which caused the integration to stop retrieving new data for some reason. Unfortunately I forgot to check my logs before doing a restart so didn't see what caused the integration to stop, and my other instance didn't see any issues.

**Comment by BottlecapDave** [comment] 2024-02-16 18:05
Regarding your original issue, this should be resolved in the next update :)

**Comment by BottlecapDave** [comment] 2024-02-17 08:16
Hello. This original issue should now be fixed in 10.1.1.

**Closed by BottlecapDave** 2024-02-17 08:16 UTC
Labels: bug

**Comment by gcoan** [comment] 2024-02-17 09:46
Thanks, I've installed the upgrade and it appears to be working fine.  Hard to prove the bug is fixed unless Octopus change my account again!

Cheers
