### ISSUE TITLE
Incorrect cost in energy dashboard when using energy import current cost and consumption 

### ISSUE THREAD

**Issue by wawyed** [BottlecapDave/HomeAssistant-OctopusEnergy#355] opened 2023-08-06 14:42 UTC
### Describe the bug

I've added the new sensors for current consumption and cost in version 8.0.0 to the energy dashboard so that I can track the standing charge in the cost of energy import. Unfortunately it seems like the cost value seems very wrong.

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4390806/efebd214-fc17-4227-bcdd-01ffb5ca0f86)

This is the config:

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4390806/97933c1d-cfcc-49c3-a1bd-425b24802151)

And the current values:

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4390806/af5fed49-1bb9-4759-a9b9-e2b95c2e18c1)

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/4390806/222815dc-3bee-4022-8bbe-faf78b00d7f9)

### Reproduction steps

See above screenshots

### Expected behaviour

The cost should match the one from the entity. Am i doing something wrong?

### Integration Version

8.0.0

### Home Assistant Version

Home Assistant 2023.8.1

### Fresh Install?

Not specified

### Home Assistant Logs

N/A

**Comment by BottlecapDave** [comment] 2023-08-06 15:06
Hi there. I've noticed this too today and trying to track down the issue. My energy dashboard history _suggests_ it might be a HA issue (it started for me when I updated HA to 2023.08, but this might be a coincidence). Did you have the integration installed on previous versions of the dashboard?

**Comment by wawyed** [comment] 2023-08-06 15:12
I've had the integration for a while yes. But I wasn't using the currect accumulative cost and consumption on the dashboard as that's a new feature.

**Comment by TheNeutrinoRaged** [comment] 2023-08-07 14:55
I was also getting crazy totals for current accumulative consumption + current accumulative cost so I tried switching to current price. The totals are still not correct, but maybe these sensors shouldn't be used together and that's intended behaviour?

<details><summary>screnshots</summary>

![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26345725/af136ae2-6c25-4d94-b8dd-421052880538)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26345725/bbce35b3-162d-4566-8fa6-283fe05cbcd7)
![image](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/26345725/2f21a06d-6cea-4a34-9cb5-8f4390cfd4c7)
</details>

**Comment by BottlecapDave** [comment] 2023-08-12 06:37
This should be resolved in the latest release (https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v8.1.0). You might not see the fix for up to 24 hours.

**Closed by BottlecapDave** 2023-08-12 06:37 UTC
Labels: bug, next-release
