### ISSUE TITLE
Intelligent peak and off-peak accumulative consumptions appear negative for first hour

### ISSUE THREAD

**Issue by legsak1mbo** [BottlecapDave/HomeAssistant-OctopusEnergy#795] opened 2024-03-14 08:35 UTC
### Describe the bug

I wanted to get a breakdown of my peak and off-peak usage and costs on Intelligent so I set the appropriate accumulative sensors (and their costs) in my energy dashboard. Since doing this the first hour has shown as (very) negative. It's almost as if something somewhere is thinking that we're in BST rather GMT and subtracting a chunk of yesterday's use for the first hour. All other hours display fine. See screenshots attached.

<img width="938" alt="Screenshot 2024-03-14 at 08 25 37" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6530330/9cd9c1ba-0827-4fcb-af20-286028a3174c">
<img width="956" alt="Screenshot 2024-03-14 at 08 25 51" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6530330/63bd6278-0bcd-4961-9e7d-a1a22eb3265e">

### Reproduction steps

Enable the peak and off-peak accumulative sensors and their costs and configure them as grid consumption sources in the energy dashboard.

### Expected behaviour

The graphs should provide an accurate breakdown of peak and off-peak costs.

### Tariff Code

INTELLI-VAR-22-10-14

### Integration Version

10.1.4

### Home Assistant Version

2024.3.0

### Fresh Install?

Not specified

### Home Assistant Logs

I've enabled debug logging and can update with logs when available.

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by legsak1mbo** [comment] 2024-03-15 09:31
Got another large negative value this morning:-

<img width="1245" alt="Screenshot 2024-03-15 at 09 29 52" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6530330/bd8e2a58-97b1-4510-82b8-e4febe18b6be">

Debug logs attached.

[octopus_ha.log](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/files/14613481/octopus_ha.log)

Happy to provide any other info as necessary.

**Comment by BottlecapDave** [comment] 2024-04-06 14:35
Hello and sorry for the late response.

I'll try and take a look when I get a chance.

**Comment by BottlecapDave** [comment] 2024-04-14 11:26
I seem to have the same issue on my instance. After a little bit of investigation, it looks like the `last_reset` timestamp isn't being updated (mine is stuck in february), despite the entity being configured in exactly the same way as the standard consumption sensor. The only difference is the peak/off peak entities are not enabled by default. Trying to track down why it's stuck and not updating on my instance. Do your entities have the same issue?  This can be confirmed by looking at the attributes in the developer tools.

**Comment by legsak1mbo** [comment] 2024-04-14 12:18
Yes indeed, both the Peak & Off Peak Current Accumulative Consumption entities are showing as last_reset 2024-03-12T00:00:00+00:00 (which is, I assume, when I enabled them).

**Comment by BottlecapDave** [comment] 2024-04-15 08:03
This should be fixed as part of v10.3.0

**Closed by BottlecapDave** 2024-04-15 08:03 UTC
Labels: bug

**Comment by legsak1mbo** [comment] 2024-05-07 08:57
Sorry to be the bearer of bad news but this happened again last night. I'd plugged in earlier than usual and got some extra charge slots - not sure if that's relevant. Let me know what you need from me (screenshot attached)...

<img width="1066" alt="Screenshot 2024-05-07 at 09 57 37" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/6530330/7d7cebd9-5dba-4402-97e5-c522d2347ad5">
