### ISSUE TITLE
Target Rate sensors not operating as expected

### ISSUE THREAD

**Issue by a8ree** [BottlecapDave/HomeAssistant-OctopusEnergy#329] opened 2023-07-26 07:28 UTC
### Describe the bug

I've set up three target rate sensors, to find the cheapest hour, hour and a half and two hour slots.

They have been running for a number of days. Ocassionally they fire in the last hour of the day but most times they do not fire at all.

### Reproduction steps

<img width="598" alt="Screenshot 2023-07-26 at 08 23 50" src="https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/16214109/dfc081ea-4986-481f-be19-6c85f2d94e32">

### Expected behaviour

The cheapest slots will be determined

### Tariff Code

E-1R-AGILE-FLEX-22-11-25-N

### Integration Version

7.5.2

### Home Assistant Version

Home Assistant 2023.7.3

### Fresh Install?

Fresh install

### Home Assistant Logs

binary_sensor.octopus_energy_target_octopus_cheapest_1_30hr_alldayOctopus Energy Target octopus_cheapest_1_30hr_allday | off | Name: octopus_cheapest_1_30hr_allday Hours: 1.5 Type: Continuous MPAN: 1800028785835 rolling_target: true last_rates: false is_target_export: false target_times:  overall_average_cost: 0p overall_min_cost: null overall_max_cost: null current_duration_in_hours: 0 current_average_cost: null current_min_cost: null current_max_cost: null next_time: null next_duration_in_hours: 0 next_average_cost: null next_min_cost: null next_max_cost: null icon: mdi:camera-timer friendly_name: Octopus Energy Target octopus_cheapest_1_30hr_allday
-- | -- | --
binary_sensor.octopus_energy_target_octopus_cheapest_1hr_alldayOctopus Energy Target octopus_cheapest_1hr_allday | off | Name: octopus_cheapest_1hr_allday Hours: 1 Type: Continuous MPAN: 1800028785835 rolling_target: true last_rates: false is_target_export: false target_times:  - value_inc_vat: 20.4645   valid_from: '2023-07-25T22:00:00+00:00'   valid_to: '2023-07-25T22:30:00+00:00'   tariff_code: E-1R-AGILE-FLEX-22-11-25-N   is_capped: false - value_inc_vat: 19.2045   valid_from: '2023-07-25T22:30:00+00:00'   valid_to: '2023-07-25T23:00:00+00:00'   tariff_code: E-1R-AGILE-FLEX-22-11-25-N   is_capped: false  overall_average_cost: 19.8345p overall_min_cost: 19.2045p overall_max_cost: 20.4645p current_duration_in_hours: 0 current_average_cost: null current_min_cost: null current_max_cost: null next_time: 2023-07-25T22:00:00+00:00 next_duration_in_hours: 1 next_average_cost: 19.8345p next_min_cost: 19.2045p next_max_cost: 20.4645p icon: mdi:camera-timer friendly_name: Octopus Energy Target octopus_cheapest_1hr_allday
binary_sensor.octopus_energy_target_octopus_cheapest_2hr_alldayOctopus Energy Target octopus_cheapest_2hr_allday | off | Name: octopus_cheapest_2hr_allday Hours: 2 Type: Continuous MPAN: 1800028785835 rolling_target: true last_rates: false is_target_export: false target_times:  overall_average_cost: 0p overall_min_cost: null overall_max_cost: null current_duration_in_hours: 0 current_average_cost: null current_min_cost: null current_max_cost: null next_time: null next_duration_in_hours: 0 next_average_cost: null next_min_cost: null next_max_cost: null icon: mdi:camera-timer friendly_name: Octopus Energy Target octopus_cheapest_2hr_allday

[binary_sensor.octopus_energy_target_octopus_cheapest_1_30hr_allday](https://ha.bree.co.uk:8123/developer-tools/state#)
Octopus Energy Target octopus_cheapest_1_30hr_allday
off	Name: octopus_cheapest_1_30hr_allday
Hours: 1.5
Type: Continuous
MPAN: 1800028785835
rolling_target: true
last_rates: false
is_target_export: false
target_times: 
overall_average_cost: 0p
overall_min_cost: null
overall_max_cost: null
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: null
next_duration_in_hours: 0
next_average_cost: null
next_min_cost: null
next_max_cost: null
icon: mdi:camera-timer
friendly_name: Octopus Energy Target octopus_cheapest_1_30hr_allday
[binary_sensor.octopus_energy_target_octopus_cheapest_1hr_allday](https://ha.bree.co.uk:8123/developer-tools/state#)
Octopus Energy Target octopus_cheapest_1hr_allday
off	Name: octopus_cheapest_1hr_allday
Hours: 1
Type: Continuous
MPAN: 1800028785835
rolling_target: true
last_rates: false
is_target_export: false
target_times: 
- value_inc_vat: 20.4645
  valid_from: '2023-07-25T22:00:00+00:00'
  valid_to: '2023-07-25T22:30:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-N
  is_capped: false
- value_inc_vat: 19.2045
  valid_from: '2023-07-25T22:30:00+00:00'
  valid_to: '2023-07-25T23:00:00+00:00'
  tariff_code: E-1R-AGILE-FLEX-22-11-25-N
  is_capped: false

overall_average_cost: 19.8345p
overall_min_cost: 19.2045p
overall_max_cost: 20.4645p
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: 2023-07-25T22:00:00+00:00
next_duration_in_hours: 1
next_average_cost: 19.8345p
next_min_cost: 19.2045p
next_max_cost: 20.4645p
icon: mdi:camera-timer
friendly_name: Octopus Energy Target octopus_cheapest_1hr_allday
[binary_sensor.octopus_energy_target_octopus_cheapest_2hr_allday](https://ha.bree.co.uk:8123/developer-tools/state#)
Octopus Energy Target octopus_cheapest_2hr_allday
off	Name: octopus_cheapest_2hr_allday
Hours: 2
Type: Continuous
MPAN: 1800028785835
rolling_target: true
last_rates: false
is_target_export: false
target_times: 
overall_average_cost: 0p
overall_min_cost: null
overall_max_cost: null
current_duration_in_hours: 0
current_average_cost: null
current_min_cost: null
current_max_cost: null
next_time: null
next_duration_in_hours: 0
next_average_cost: null
next_min_cost: null
next_max_cost: null
icon: mdi:camera-timer
friendly_name: Octopus Energy Target octopus_cheapest_2hr_allday

**Comment by BottlecapDave** [comment] 2023-08-01 16:42
Hi there. Sorry for the late response.

Target rate sensors only evaluate when all rates are available for the specified evaluation period (midnight to midnight in your case). Unfortunately, agile rates are only provided up to 11pm. Therefore you need to either shorten your evaluation period (e.g. 00:00 to 23:00) or shift the evaluation period to be inline with agile rates (16:00 to 16:00 as per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#fromto-times)).

I'm planning on making this clearer in the future on the sensor if the rate data for the evaluation period isn't available or making it so the sensor can evaluate when rate data is incomplete.

**Comment by netmindz** [comment] 2023-08-03 10:59
I think it would be helpful if he docs made it clearer that you *must* change the time window when using Agile

**Comment by a8ree** [comment] 2023-08-03 15:40
> Hi there. Sorry for the late response.
> 
> Target rate sensors only evaluate when all rates are available for the specified evaluation period (midnight to midnight in your case). Unfortunately, agile rates are only provided up to 11pm. Therefore you need to either shorten your evaluation period (e.g. 00:00 to 23:00) or shift the evaluation period to be inline with agile rates (16:00 to 16:00 as per the [docs](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/blob/develop/_docs/setup_target_rate.md#fromto-times)).
> 
> I'm planning on making this clearer in the future on the sensor if the rate data for the evaluation period isn't available or making it so the sensor can evaluate when rate data is incomplete.

Thanks! This sorted my issue @BottlecapDave 
Taking into account the comment from @netmindz  perhaps it would be possible where someone has selected the agile rate that 16:00 to 16:00 becomes the default value

**Comment by BottlecapDave** [comment] 2023-08-05 05:39
I've updated the docs to be clearer on agile behaviour with justification on why it's not the default value. I'll close this issue now, as it's "by design".

**Closed by BottlecapDave** 2023-08-05 05:39 UTC
Labels: bug

**Comment by a8ree** [comment] 2023-08-05 09:09
Great, thanks again @BottlecapDave

**Comment by netmindz** [comment] 2023-08-05 09:26
I disagree with your updated doc. If you are on agile, which is surely the key reason for using the target feature as the other tariffs have predictable low cost times, then if no time window is set then it doesn't work at all.

It's confusing to have an option that restricts when a low cost is triggered, that only works if data for that full period is available.

Why are you so hesitant to change the default to match the data? It wouldn't break existing setups as the default doesn't work for Agile. Making the default 23 would still give a 24 hour window, so would still be "unrestricted"

**Comment by BottlecapDave** [comment] 2023-08-12 09:15
I've been thinking about this over the last week, so sorry for the late response. 

I am personally not on agile, but use target rate sensors (along with other sensors) as I want my home to adapt to my tariff so that if I switch I don't have to update my home. Granted, I am probably in the minority, but I can't guarantee everyone who uses this feature is on agile. But you're probably correct in saying the majority probably are.

The main issue with the enforcing of target rate sensors is that while fine at initial creation, after creation is where the problem can lie. If a user switches tariffs (from another tariff to agile or agile to another tariff), I don't want default behaviour of target rate sensors to change automatically without their knowledge, as this will lead to potential frustration and probably more bugs raised. I also don't want to do anything that will change behaviour automatically for those that have set it up already as this will be a breaking change in the integration and lead down the same route as previously mentioned.

My current plan in a future release is as follows
1. Update the adding/updating of target rate sensors to report useful error if a user's sensor falls into the "dark zone" (23:00-00:00) if they are on agile. This is a bit complicated as users can setup target rate sensors overnight which would be valid starting at 23:00. I _think_ however it's just the `to` time I need to worry about.
2. Add an attribute to target rate sensors to indicate if all required rate data is available for the target period. This is useful for debugging purposes and for other tariffs (if for instance the integration cant get the latest rates)
3. Use [HA's repair mode](https://www.home-assistant.io/integrations/repairs/) to guide users to update their target rate sensors if they fall into the "dark zone" and they're on agile. This will help guide existing users to fix their sensors, as well as any other users who might switch over to agile from other tariffs.
