### ISSUE TITLE
Octopus Energy integration failed to setup 

### ISSUE THREAD

**Issue by wyclef77** [BottlecapDave/HomeAssistant-OctopusEnergy#488] opened 2023-10-25 16:50 UTC
### Describe the bug

Integration is installed and works for a day, but roughly after 24 hours I am getting this 

![Screenshot 2023-10-25 at 17 47 21](https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/assets/43586945/e5efe1dc-d6f1-428a-9bd7-c05bb8815ec5)

### Reproduction steps

x

### Expected behaviour

Integration to work without getting this message ebery 24 hours. 

### Integration Version

8.4.4

### Home Assistant Version

Home Assistant 2023.10.3

### Fresh Install?

Fresh install

### Home Assistant Logs

Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 5:30:58 AM (1 occurrences)
Last logged: 5:30:58 AM

Error setting up entry Account for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 81, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 125, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 351, in async_get_account
    account_response_body = await self.__async_read_response__(account_response, url)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 963, in __async_read_response__
    raise ServerError(msg)
custom_components.octopus_energy.api_client.ServerError: DO NOT REPORT - Octopus Energy server error (https://api.octopus.energy/v1/graphql/): 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by BottlecapDave** [comment] 2023-10-25 17:35
Alternatively, if you're comfortable to run some graphql queries at https://api.octopus.energy/v1/graphql/, it might shed if there's anything wrong with your account.

You'll need to run this first query to get a valid access token

```
mutation {
	obtainKrakenToken(input: { APIKey: "YOUR_API_TOKEN_GOES_HERE"}) {
		token
	}
}
```

You then take the result from the `token` field and add the following to the `header` tab

```
{
  "Authorization": "JWT <<YOUR_ACCESS_TOKEN>>"
}
``

with the following query

```
query {
  account(accountNumber: "YOUR_ACCOUNT_ID_GOES_HERE") {
    electricityAgreements(active: true) {
			meterPoint {
				mpan
				meters(includeInactive: false) {
          makeAndType
					serialNumber
          makeAndType
          meterType
          smartExportElectricityMeter {
						deviceId
            manufacturer
            model
            firmwareVersion
					}
          smartImportElectricityMeter {
						deviceId
            manufacturer
            model
            firmwareVersion
					}
				}
				agreements {
					validFrom
					validTo
					tariff {
						...on StandardTariff {
							tariffCode
              productCode
						}
						...on DayNightTariff {
							tariffCode
              productCode
						}
						...on ThreeRateTariff {
							tariffCode
              productCode
						}
						...on HalfHourlyTariff {
							tariffCode
              productCode
						}
            ...on PrepayTariff {
							tariffCode
              productCode
						}
					}
				}
			}
    }
    gasAgreements(active: true) {
			meterPoint {
				mprn
				meters(includeInactive: false) {
					serialNumber
          consumptionUnits
          modelName
          mechanism
          smartGasMeter {
						deviceId
            manufacturer
            model
            firmwareVersion
					}
				}
				agreements {
					validFrom
					validTo
					tariff {
						tariffCode
            productCode
					}
				}
			}
    }
  }
}
```

If the response as the word `errors`, then paste the results here

**Comment by wyclef77** [comment] 2023-10-25 18:03
Actually done it - those are the results: 

{
  "errors": [
    {
      "message": "Value of 'Authorization' header is not a valid credential.",
      "locations": [
        {
          "line": 34,
          "column": 8
        }
      ],
      "path": [
        "account"
      ],
      "extensions": {
        "errorType": "AUTHORIZATION",
        "errorCode": "KT-CT-1143",
        "errorDescription": "The value of the HTTP Authorization header is not recognized as a valid access credential for this API.  Valid credentials can be generated by calling the obtainKrakenToken mutation."
      }
    }
  ],
  "data": {
    "account": null
  }

**Comment by BottlecapDave** [comment] 2023-10-25 18:34
That error _suggests_ you didn't use the token response from the first request in header for the second request (these are two different keys)

**Comment by terencekmchan** [comment] 2023-12-05 06:41
I have similar issue and my GraphQL response as follow. any idea??

{
  "errors": [
    {
      "message": "Unauthorized.",
      "locations": [
        {
          "line": 33,
          "column": 3
        }
      ],
      "path": [
        "account"
      ],
      "extensions": {
        "errorType": "AUTHORIZATION",
        "errorCode": "KT-CT-1111",
        "errorDescription": "The viewer is not authorized to execute the query/mutation. Check authentication or roles/permissions."
      }
    }
  ],
  "data": {
    "account": null
  }
}

**Comment by smithbill17** [comment] 2023-12-05 08:20
I'm now getting this *exact* issue described above.

I had this integration all working previously, but had to 'rebuild' my HomeAssistant server, so just yesterday I re-setup the OE integration and it was all working fine. I then went out for an hour, came home & found the integration had stopped working & the log has this "bad gateway" error.

I eventually figured out how to use your instructions correctly to get a token & response back from graphql. It did NOT return any "errors", only a structure listing my Agreements & Meter points (not pasted here).

So then I went back to HomeAssistant and tried to 'ReLoad' the integration. It didn't work & logged this error (account number removed):

[Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 08:00:59 (1 occurrences)
Last logged: 08:00:59

Error setting up entry A-Cxxxxxxx for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 83, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 127, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 400, in async_get_account
    await self.async_refresh_token()
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 385, in async_refresh_token
    async with client.post(url, json=payload) as token_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError](url)

I've no idea what this meant, so just restarted HomeAssistant and once again the OE integration fails to load and gives the "Bad Gateway" error.

What's going on? Why did it just suddenly stop working while I was out? How do I fix it?

**Comment by smithbill17** [comment] 2023-12-05 12:00
Okay, I think the problem I was having (as described above) has just 'gone away' as the integration has reloaded and appears to be working.

So presumably "Bad Gateway" has been an issue with OE servers??

**Comment by Jilas** [comment] 2023-12-19 15:57
Not sure if this is related, but with version v9.1.0 whenever I restart the HA server the octopus integration "Failed to Setup".

Some combination of ignoring it and waiting for 3-10 minutes after a restart, and only then will a reload work.  I do run two servers, a test box with 4 poll's an hour, the main  that is doing it every 2 minute/15 minute polls (so it's not an api cap).   I know the Octopus side is ok, as the issue is just with the box that's restarted.

Checking the logs I get the message below which is similar to the earlier posted versions.

2023-12-19 15:44:33.477 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry x-xxxxxxxx for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 83, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 127, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 407, in async_get_account
    async with client.post(url, json=payload, headers=headers) as account_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 960, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

Hope this helps.

**Comment by BottlecapDave** [comment] 2023-12-22 06:49
Closing as all reported logs point at slow or unresponsive octopus energy APIs

**Closed by BottlecapDave** 2023-12-22 06:49 UTC
Labels: bug
