### ISSUE TITLE
Agile rates haven’t refreshed 

### ISSUE THREAD

**Issue by djdarlo** [BottlecapDave/HomeAssistant-OctopusEnergy#640] opened 2023-12-17 17:40 UTC
### Describe the bug

The agile rates usually refresh after 4pm. They have refreshed in the octopus app but not in the integration yet (17:40). I’ve done a restart to see if they helped but it didn’t.  It’s the rate card which isn’t displaying the updating values. Looks like the values are updated in the back end as my target times are updated. 

### Reproduction steps

Na

### Expected behaviour

Na

### Tariff Code

Na

### Integration Version

Latest

### Home Assistant Version

Latest

### Fresh Install?

Not specified

### Home Assistant Logs

Na

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by dannytsang** [comment] 2023-12-17 18:44
Same here. Suspect this this the stack trace that's most relevant (redacted serial and other meter info). If you need the full debug log, let me know and I will sanitize it before uploading.

```
2023-12-17 18:30:33.636 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.octopus_energy_electricity_XXXXXX_YYYYYYYY_previous_accumulative_cost_override fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/octopus_energy/electricity/previous_accumulative_cost_override.py", line 129, in async_update
    [rate_data, standing_charge] = await asyncio.gather(
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 676, in async_get_electricity_rates
    return await self.async_get_electricity_standard_rates(product_code, tariff_code, period_from, period_to)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 620, in async_get_electricity_standard_rates
    data = await self.__async_read_response__(response, url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 1136, in __async_read_response__
    raise ServerError(msg)
custom_components.octopus_energy.api_client.ServerError: DO NOT REPORT - Octopus Energy server error (https://api.octopus.energy/v1/products/AGILE-FLEX-22-11-25/electricity-tariffs/E-1R-AGILE-FLEX-22-11-25-A/standard-unit-rates?period_from=2023-12-16T00:00:00Z&period_to=2023-12-17T00:00:00Z&page=1): 502; <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by dannytsang** [comment] 2023-12-17 18:47
Ugh, just spotted and this could be duplicate of  #624

**Comment by BottlecapDave** [comment] 2023-12-17 18:54
Hello. For the errors you stated in your logs, this is due to the APIs either not responding at all or not responding in a timely manner so theres very little I can do. The next update should hopefully elevate this somewhat once everyone is moved across.

**Comment by borpin** [comment] 2023-12-17 20:40
Not getting the agile rates. Upgraded to beta 2 and still nothing (repeated restarts to force fetch).

I think the integration thinks it has been successful

```
2023-12-17 20:28:54.739 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_xxxxxxxxxxxxxxxxxxxxx data in 0.000 seconds (success: True)
```
But the state for the `next_day_rates` for electric is `2023-12-17T16:00:08.233+00:00`

State of the gas is correct.

There are a lot of log entries so it isn't easy to work out what refers to what :(

**Comment by BottlecapDave** [comment] 2023-12-17 21:21
The first message you're stating is reported by HA and not the integration. The final set of messages contain messages raised by the integration (the first one) and by HA (the second message). The integration runs updates every minute, but keeps track of its own times for when to retrieve information from the OE servers. The integration can fail whereas a manual request can succeed for a number of reasons like contention of HA instance, server errors or slow responses from the servers. The integration also pulls rate information for three days, so it might be that one of the requests is failing. 

If you are on the latest beta (which imo is more stable then the current version), you are looking for warnings with failed requests with status codes (e.g. 400).

The event entities and the data retrieved attributes on the rate sensors will state when the rates were last successfully retrieved, which in your example implies 4pm

**Comment by captainboatsinkrawr** [comment] 2023-12-17 23:41
Hi - Hope this feedback helps: I've had this issue on the official version.  Target rate entities updating correctly but agile rates card only going to 10:30pm and then blank after 11pm.  Installed the beta at 11:10pm - at 11:31pm the agile rates card started displaying the rates again.  I would say the beta likely fixed it, but in previous days the rates have come back randomly. Time will tell.  Thank you for the hard work Dave!

**Comment by borpin** [comment] 2023-12-18 06:54
Him @BottlecapDave - thanks for the info.

Perhaps a different error message when it expects to find rates and it doesn't. So after 5pm, if `next_day_rates` doesn't have any data, raise a different error? 

It eventually retrieved the data at `2023-12-18T04:30:34.676+00:00`.

```
2023-12-18 04:29:25.588 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Failed to retrieve new electricity rates for 1800060553178/23J0215943, so using cached rates
2023-12-18 04:29:25.588 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_1800060553178_23J0215943 data in 0.000 seconds (success: True)
2023-12-18 04:30:34.664 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Electricity rates retrieved for 1800060553178/23J0215943 (E-1R-AGILE-FLEX-22-11-25-N);
2023-12-18 04:30:34.664 DEBUG (MainThread) [custom_components.octopus_energy.coordinators.electricity_rates] Finished fetching ELECTRICITY_RATES_1800060553178_23J0215943 data in 9.077 seconds (success: True)
```

**Comment by BottlecapDave** [comment] 2023-12-18 20:41
The sensor needs to support lots of different tariffs and I try to avoid having tariff specific information as it can be flakey. The displayed error around caches is stating that the rates can't be retrieved in itself. The event entity will only update it's state when it successfully retrieves rate information, so you can always setup an automation to monitor this entity.

**Comment by BottlecapDave** [comment] 2023-12-22 06:42
Closing as this was caused by instability in the API and the latest update has improved recovery when failing to retrieve data. Once more people upgrade to the latest version the API should become more stable.

**Closed by BottlecapDave** 2023-12-22 06:42 UTC
Labels: bug
