### ISSUE TITLE
Intelligent dispatching is now "unavailable"

### ISSUE THREAD

**Issue by rbrooklyn** [BottlecapDave/HomeAssistant-OctopusEnergy#637] opened 2023-12-17 10:46 UTC
### Describe the bug

Hello,

Yesterday at some point, the intelligent_dispatching sensor went to an unavailable state. This caused various automations to fail, which was mildly annoying.

I think this has been caused by me switching off Smart Charging for my electric vehicle, and it might have also been triggered by a home assistant upgrade I did. This would normally be gracefully handled by the addon, however, I've had this turned off for several days now and I think the API is no longer returning data that the addon needs. This is causing it to crash. I have attached a home assistant log as requested.

I believe the fix would be a fairly simple "check if I have this data and then gracefully carry on without it if I don't" situation instead of expecting the dispatches to always be present.

Turning on smart charging has fixed the problem immediately (including with the newest public version of home assistant), and I'm now seeing the state as being "off", which is expected for this time of the day.

### Reproduction steps

- Turn off smart charging on the Octopus App
- Wait for several days (5-6 days in my case)
- Intelligent dispatching will go to unknown. Upgrading or restarting Home Assistant may or may not be a factor in this as well

### Expected behaviour

Intelligent dispatching should not be unavailable 

### Tariff Code

E-1R-INTELLI-VAR-22-10-14-A

### Integration Version

9.1.0

### Home Assistant Version

2023.12.3

### Fresh Install?

After upgrading

### Home Assistant Logs

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/octopus_energy/intelligent/dispatching.py:78
Integration: Octopus Energy (documentation, issues)
First occurred: 10:25:53 AM (11 occurrences)
Last logged: 10:36:10 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 745, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 845, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 786, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 751, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 227, in state
    if (is_on := self.is_on) is None:
                 ^^^^^^^^^^
  File "/config/custom_components/octopus_energy/intelligent/dispatching.py", line 78, in is_on
    self._state = is_in_planned_dispatch(current_date, result.dispatches.planned) or is_off_peak(current_date, rates)
                                                       ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dispatches'

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by garethcook** [comment] 2023-12-18 20:17
I'm getting total failure of the add-on, also the HACS Octopus Intelligent add-on also failing. Highly likely something at the Octopus end is failing or the API has changed?

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 19:45:10 (2 occurrences)
Last logged: 20:13:19

Error setting up entry A-xxxxxxx for octopus_energy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/__init__.py", line 83, in async_setup_entry
    await async_setup_dependencies(hass, config)
  File "/config/custom_components/octopus_energy/__init__.py", line 127, in async_setup_dependencies
    account_info = await client.async_get_account(config[CONFIG_MAIN_ACCOUNT_ID])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/octopus_energy/api_client/__init__.py", line 407, in async_get_account
    async with client.post(url, json=payload, headers=headers) as account_response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

**Comment by BottlecapDave** [comment] 2023-12-18 20:36
Yeah it's failing due to timeouts with the API which is out of my control. By having both integrations installed you might also be hitting other limits applied to your account as they'll both be doing lots of API calls within a short period of time.

**Comment by garethcook** [comment] 2023-12-18 21:09
There's my compelling reason to act :-) Just remapping my scripts now, will revert to your add-on. Thanks, Dave.

**Comment by garethcook** [comment] 2023-12-19 08:38
Reworked my scripts last night, removed the other add-on, all fine. This morning, restarted HA after working on something else, and all the entities were unavailable. Waiting 5 minutes, restarted the plugin and they were back.

**Comment by BottlecapDave** [comment] 2023-12-20 07:52
The API seems to be only getting worse at either dropping connections or hitting timeouts, or HA is getting worse at handling multiple connections. I personally rarely hit any issues initiallising the integration, but then I only access OE exclusively via this integration (with the odd time looking at the app) and I only have one instance running. I plan to try and improve the initialisation, potentially increasing the timeout just for start up.

**Comment by BottlecapDave** [comment] 2023-12-20 17:49
@rbrooklyn I believe this issue _should_ be fixed in the latest release (v9.2.1)

**Comment by owenashurst** [comment] 2024-01-01 15:02
@BottlecapDave could this have caused a regression at all? I have an issue here now #663

**Comment by BottlecapDave** [comment] 2024-01-02 06:43
@owenashurst that issue is different and therefore not related.

**Comment by BottlecapDave** [comment] 2024-01-30 06:52
Using as this should be resolved.

**Closed by BottlecapDave** 2024-01-30 06:52 UTC
Labels: bug
