### ISSUE TITLE
Does this Integration support agile outgoing for export?

### ISSUE THREAD

**Issue by maegibbons** [BottlecapDave/HomeAssistant-OctopusEnergy#61] opened 2022-09-04 02:34 UTC
Does this Integration support agile outgoing for export?

Krs

Mark

**Comment by BottlecapDave** [comment] 2022-09-04 10:03
Hello.

This integration should create sensors for both your import and export. The issue is it's harder to test for tariffs that I'm not on.

If there are any issues, let me know.

Thanks,
Dave

**Comment by maegibbons** [comment] 2022-09-04 10:51
Thanks for the prompt reply.

Do you create sensors for best time to export for a certain period block?  I.e the highest priced block?

I wasn't sure if this was handled from a brief look at the code.

If the answer is a YES then I will get on and download and answer all my other questions myself!

Krs

Mark

**Comment by BottlecapDave** [comment] 2022-09-10 08:41
You can create binary sensors (referred to as target rates), which I believe can target your export sensors. However, I don't have this setup and so this functionality was contributed by another user, so this might not be working as intended (e.g. picking the point where the price is lowest instead of highest). It would be great if you had a chance to try out the integration and raise any issues in this area that need fixing :)

**Comment by andyvirus** [comment] 2022-10-26 15:53
I can confirm that now I have 2 MPAN numbers (one import one export) both are shown in the integration as different devices. Rates are stored in the attributes of the sensors. I have not tried target rates yet on either import or export so will have a play and update. Just need to figure out how to pull the data from the attributes into a nice card but thats a different issue. For the question "Does this integration support agile outgoing for export" I can confirm this is a hard yes. To what extent, different question but any issues I will assume this issue should be closed and any issue relating to the support should be a different issue entirely. Thanks for this @BottlecapDave

**Comment by usbrit** [comment] 2022-11-28 20:51
@BottlecapDave 
Just tested this for Export (already using it for Import).
Unfortunately it shows lowest rates, not highest.
Please could you take a look as this would be incredibly useful?
Thanks

**Comment by BottlecapDave** [comment] 2022-12-03 10:26
Sorry to hear this isn't working @usbrit. I'm taking a look now, but it would be useful if you could send me some diagnostics of your setup so that I have an idea of what data I'm working with.

You can download diagnostics of your account by going to your electricity meter device by
1) Navigate to http://bottlecapha.local:8123/config/devices/dashboard
2) Search for `octopus`
3) Click on the device titled Electricity Meter
4) Click Download diagnostics
5) Upload file here.

**Comment by usbrit** [comment] 2022-12-03 11:48
@BottlecapDave Update: so have figured timers work on export BUT are finding the lowest tariffs rather than the highest. So I have set a 22 hour timer which is ON for the worst export times on flips OFF for the best. Not ideal, but it works. Could you add a toggle on the UI to flip the logic for export meters instead? 

Thanks for providing this, really makes life easy for charge/discharge times. 
![Screenshot_2022-12-03-11-47-45-64_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/53425475/205439438-36db7a5c-c001-44e8-827e-f8f0063017d8.jpg)

**Comment by usbrit** [comment] 2022-12-03 15:28
> Sorry to hear this isn't working @usbrit. I'm taking a look now, but it would be useful if you could send me some diagnostics of your setup so that I have an idea of what data I'm working with.
> 
> You can download diagnostics of your account by going to your electricity meter device by
> 
> 1. Navigate to http://bottlecapha.local:8123/config/devices/dashboard
> 2. Search for `octopus`
> 3. Click on the device titled Electricity Meter
> 4. Click Download diagnostics
> 5. Upload file here.

Here's the diagnostics too
`{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.10.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.5",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "5.15.61-v7",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.2",
    "docker_version": "20.10.17",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "octopus_energy": {
      "version": "4.6.4",
      "requirements": []
    },
    "mass": {
      "version": "2022.11.0",
      "requirements": [
        "music-assistant==1.8.7",
        "git+https://github.com/music-assistant/databases@fix-breaking-sqlalchemy-cursor-changes#databases==0.6.2"
      ]
    },
    "solis": {
      "version": "3.1.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "hildebrandglow_dcc": {
      "version": "0.6.0",
      "requirements": []
    },
    "octopusagile": {
      "version": "2022.10.0b0",
      "requirements": []
    },
    "solarman": {
      "version": "1.0.0",
      "requirements": [
        "pyyaml"
      ]
    },
    "nodered": {
      "version": "1.1.2",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "config_flow": true,
    "documentation": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "zeroconf": [],
    "homekit": {},
    "dependencies": [],
    "codeowners": [
      "@bottlecapdave"
    ],
    "version": "4.6.4",
    "iot_class": "cloud_polling",
    "is_built_in": false
  },
  "data": {
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": true,
            "is_smart_meter": true
          }
        ],
        "agreements": [
          {
            "valid_from": "2022-07-16T23:00:00+00:00",
            "valid_to": "2023-07-16T23:00:00+00:00",
            "tariff_code": "E-1R-AGILE-OUTGOING-19-05-13-A"
          }
        ]
      },
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true
          }
        ],
        "agreements": [
          {
            "valid_from": "2022-06-30T23:00:00+00:00",
            "valid_to": "2023-06-30T23:00:00+00:00",
            "tariff_code": "E-1R-AGILE-18-02-21-A"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**"
          }
        ],
        "agreements": [
          {
            "valid_from": "2021-05-27T23:00:00+00:00",
            "valid_to": null,
            "tariff_code": "G-1R-VAR-21-04-09-A"
          }
        ]
      }
    ]
  }
}`

**Comment by BottlecapDave** [comment] 2022-12-04 15:14
Hello @usbrit - This should be fixed with https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/releases/tag/v4.7.0

**Comment by usbrit** [comment] 2022-12-04 19:45
![Screenshot_2022-12-04-19-43-30-99_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/53425475/205511890-f15bbf1f-c9d1-4efb-9030-e4a5693b946b.jpg)
@BottlecapDave tested and confirmed to be working 👍🏻👍🏻 Thanks!

**Comment by BottlecapDave** [comment] 2022-12-05 17:38
Excellent. Thanks for reporting back.

**Closed by BottlecapDave** 2022-12-05 17:38 UTC
Labels: bug, question, awaiting release confirmation
