### ISSUE TITLE
Current rate isn't reflecting smart charging rate

### ISSUE THREAD

**Issue by samwise22** [BottlecapDave/HomeAssistant-OctopusEnergy#699] opened 2024-01-10 19:34 UTC
### Describe the bug

Before this week whenever Octopus gave me a smart charging plan the 'current rate' sensor would update during the charging window to reflect the lower rate in effect. Now it's not doing that and instead remaining on the peak rate. The sensor is showing an update timestamp within the charging plan window so I know it's not just that it's no ot refreshing. 

Octopus is clear that any smart charging during peak hours is charged at the lower rate (except if I bump charge). Is the API giving incorrect data or is something off in the integration?

### Reproduction steps

Observe the peak rate in the 'current rate' sensor, create a smart charging plan and wait for a charging session within peak hours. Observe the current rate sensor to see it remains at peak rate

### Expected behaviour

Current rate sensor should reflect the cheaper off peak rate 

### Tariff Code

Intelligent Octopus Go

### Integration Version

10.0.2

### Home Assistant Version

2024.1.2

### Fresh Install?

Not specified

### Home Assistant Logs

N/a

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by BottlecapDave** [comment] 2024-01-10 19:45
Hello. This is a known issue and duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/687. Please follow of explainations and updates on the issue.

**Closed by BottlecapDave** 2024-01-10 19:45 UTC
Labels: bug
