### ISSUE TITLE
Oversized attributes

### ISSUE THREAD

**Issue by simonjgreen** [BottlecapDave/HomeAssistant-OctopusEnergy#408] opened 2023-09-17 14:41 UTC
### Describe the bug

I've just spotted warnings in my log that attributes are not being stored due to being oversized.

### Reproduction steps

I don't have a way to force this to reproduce, but it is repeating in my logs

### Expected behaviour

n/a

### Tariff Code

 E-1R-FLUX-EXPORT-23-02-14-H

### Integration Version

8.2.0

### Home Assistant Version

2023.8.1

### Fresh Install?

Not specified

### Home Assistant Logs

```
Log Details (WARNING)
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:584
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 11:03:14 AM (8 occurrences)
Last logged: 11:03:16 AM

State attributes for sensor.octopus_energy_electricity_xxxxx_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for sensor.octopus_energy_electricity_xxxxx_export_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for sensor.octopus_energy_gas_xxxxx_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
```

**Comment by BottlecapDave** [comment] 2023-09-17 15:20
Thanks for reporting. This is a duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/357, so closing.

**Closed by BottlecapDave** 2023-09-17 15:20 UTC
Labels: bug
