### ISSUE TITLE
Overriding deprecated methods

### ISSUE THREAD

**Issue by johnthomas22** [BottlecapDave/HomeAssistant-OctopusEnergy#321] opened 2023-07-22 07:10 UTC
### Describe the bug

2023-07-21 20:19:34.909 WARNING (MainThread) [homeassistant.components.number] custom_components.octopus_energy.intelligent.charge_limit::OctopusEnergyIntelligentChargeLimit is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

### Reproduction steps

Add this sensor.

### Expected behaviour

Message should not apepear in the logs. 

### Integration Version

Latest

### Home Assistant Version

Up-to-date

### Fresh Install?

Not specified

### Home Assistant Logs

2023-07-21 20:19:34.909 WARNING (MainThread) [homeassistant.components.number] custom_components.octopus_energy.intelligent.charge_limit::OctopusEnergyIntelligentChargeLimit is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by BottlecapDave** [comment] 2023-07-22 07:11
Thanks for raising. Duplicate of https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/313

**Closed by BottlecapDave** 2023-07-22 07:11 UTC
Labels: bug
