### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by marcuslib** [BottlecapDave/HomeAssistant-OctopusEnergy#677] opened 2024-01-05 10:09 UTC
### Describe the bug

Since i have updated home assistant to 2024.1.0 and HomeAssistant-OctopusEnergy to 10.0 target rates has stopped working, when I click configure, I get Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble. i can create a new one, but does not work and when I click configure, I get the same 500 error

### Reproduction steps

click add entry, then target rate, fill in details, click submit, then click configure, get error.

### Expected behaviour

be able to click configure - also does not pick up cheapest times during day

### Tariff Code

n/a

### Integration Version

10.0

### Home Assistant Version

2024.1.0

### Fresh Install?

Not specified

### Home Assistant Logs

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.1.0",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "6.1.70-haos",
    "supervisor": "2023.12.0",
    "host_os": "Home Assistant OS 11.3",
    "docker_version": "24.0.7",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {
    "octopusagile": {
      "version": "2021.3.0b0",
      "requirements": []
    },
    "ecoflow_cloud": {
      "version": "0.12.4",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "tuya_local": {
      "version": "2023.12.2",
      "requirements": [
        "tinytuya==1.13.1"
      ]
    },
    "localtuya": {
      "version": "5.2.1",
      "requirements": []
    },
    "remote_homeassistant": {
      "version": "3.11",
      "requirements": []
    },
    "octopus_energy": {
      "version": "10.0.0",
      "requirements": []
    },
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "eon_next": {
      "version": "0.1.0",
      "requirements": []
    },
    "tapo": {
      "version": "2.12.2",
      "requirements": [
        "plugp100==4.0.1"
      ]
    },
    "powercalc": {
      "version": "v1.9.14",
      "requirements": [
        "numpy>=1.21.1"
      ]
    }
  },
  "integration_manifest": {
    "domain": "octopus_energy",
    "name": "Octopus Energy",
    "codeowners": [
      "@bottlecapdave"
    ],
    "config_flow": true,
    "dependencies": [
      "repairs",
      "recorder"
    ],
    "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
    "homekit": {},
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues",
    "ssdp": [],
    "version": "10.0.0",
    "zeroconf": [],
    "is_built_in": false
  },
  "data": {
    "id": "A-6E9862ED",
    "octoplus_enrolled": true,
    "electricity_meter_points": [
      {
        "mpan": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1031 - Secure Meters UK",
            "model": "C0A10102",
            "firmware": "C0A10003"
          },
          {
            "serial_number": "**REDACTED**",
            "is_export": false,
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1125 - Shenzhen Kaifa Metering",
            "model": "31324131",
            "firmware": "17101917"
          }
        ],
        "agreements": [
          {
            "start": "2023-10-26T23:00:00+00:00",
            "end": null,
            "tariff_code": "E-1R-AGILE-FLEX-22-11-25-M",
            "product_code": "AGILE-FLEX-22-11-25"
          }
        ]
      }
    ],
    "gas_meter_points": [
      {
        "mprn": "**REDACTED**",
        "meters": [
          {
            "serial_number": "**REDACTED**",
            "consumption_units": "m\u00b3",
            "is_smart_meter": true,
            "device_id": "**REDACTED**",
            "manufacturer": "1031 - Secure Meters UK",
            "model": "B0A10144",
            "firmware": "09000000"
          }
        ],
        "agreements": [
          {
            "start": "2023-10-24T23:00:00+00:00",
            "end": null,
            "tariff_code": "G-1R-VAR-22-11-01-M",
            "product_code": "VAR-22-11-01"
          }
        ]
      }
    ]
  }
}

### Confirmation

- [X] I confirm that I cannot find my solution within the [documentation](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy)
- [X] I confirm that I cannot find my solution within the [FAQ](https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy/faq)

**Comment by darrenmcuk** [comment] 2024-01-05 12:37
Same here

**Comment by marcuslib** [comment] 2024-01-05 12:48
i rebooted and looks to be working, but still get the error when clicking configure

**Comment by markcocker** [comment] 2024-01-05 18:03
I get the same error when clicking on `Configure` for target rates.
However I can successfully use`Configure` for devices (accounts).

**Comment by marcuslib** [comment] 2024-01-05 18:21
Other users are getting the same on facebook group Octopus Energy Automations (Unofficial) https://www.facebook.com/groups/877587433965599**

**Comment by BottlecapDave** [comment] 2024-01-05 18:44
Hello. Thanks for reporting and I know what the issue is. I'll try and get a fix out over the weekend. This should only be effecting the updating of existing target rate sensors, but the sensors themselves should still be functional.

**Comment by marcuslib** [comment] 2024-01-05 18:46
@BottlecapDave Thank you, also if you get a chance, have a look at facebook group https://www.facebook.com/groups/877587433965599, we are all using your integration.

**Comment by marcuslib** [comment] 2024-01-05 18:46
@BottlecapDave Thank you, also if you get a chance, have a look at facebook group https://www.facebook.com/groups/877587433965599, we are all using your integration.

**Comment by BottlecapDave** [comment] 2024-01-06 19:44
This should now be resolved in v10.0.1. Sorry for the inconvience.

**Closed by BottlecapDave** 2024-01-06 19:44 UTC
Labels: bug

**Comment by marcuslib** [comment] 2024-01-06 20:34
Thank you, please check out our group, we all use your integration https://www.facebook.com/groups/877587433965599
