### ISSUE TITLE
Latest HA 2023-11 Warning Logs showing up

### ISSUE THREAD

**Issue by thorrrr** [BottlecapDave/HomeAssistant-OctopusEnergy#502] opened 2023-11-02 09:57 UTC
### Describe the bug

After update multiole warning logs FYI

### Reproduction steps

Warning  Logs  FYI

### Expected behaviour

No Warnings or Errors  :)

### Integration Version

Latest

### Home Assistant Version

2023-11

### Fresh Install?

After upgrading

### Home Assistant Logs

Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:578
Integration: Recorder (documentation, issues)
First occurred: 1 November 2023 at 22:09:23 (4307 occurrences)
Last logged: 09:51:31

State attributes for sensor.octopus_energy_electricity_17p5604074_1300004118991_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for sensor.octopus_energy_gas_g4p56045261700_1671692907_current_rate exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
State attributes for camera.xiaomi_cloud_map_extractor exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored

**Comment by BottlecapDave** [comment] 2023-11-02 13:08
Hello. One of them isn't caused by this integration ( camera.xiaomi_cloud_map_extractor). The other two are already covered by https://github.com/BottlecapDave/HomeAssistant-OctopusEnergy/issues/357, so closing as duplicate :)

**Closed by BottlecapDave** 2023-11-02 13:08 UTC
Labels: bug
